Introduzione norme di progetto
SWEasabi/norme-di-progetto pull request #30
Opened 2023-03-17 15:57 UTC by bonni1207

2023-03-21 14:26 UTC, pierobonluca01 requested changes

2023-03-21 14:26 UTC, pierobonluca01 commented on src-doc/contenuti/introduzione.tex
> +Un glossario utile con alcune definizioni per lavorare al progetto al fine di chiarire eventuali termini che possono generare dubbi interpretativi:
Togliere e rimandare a documento Glossario dedicato.

2023-03-21 20:53 UTC, bonni1207 commented on src-doc/contenuti/introduzione.tex
> +Un glossario utile con alcune definizioni per lavorare al progetto al fine di chiarire eventuali termini che possono generare dubbi interpretativi:
Fatto

2023-03-22 13:39 UTC, casYy approved these changes
sembra corretto

2023-03-22 13:41 UTC, merged